In [1]:
import pandas as pd
from src.constants import DATA_DIR


pd.options.display.max_columns = 100
pd.options.display.max_rows = 200

In [2]:
df = pd.read_csv(DATA_DIR / "merged_data.csv")

/var/folders/wx/6l7zgh9x4cd0fjqhbd7hzs_00000gn/T/ipykernel_71917/3572216794.py:1: DtypeWarning: Columns (25,57,58,72) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DATA_DIR / "merged_data.csv")

In [3]:
from src.models import MovingAverageModel

In [4]:
df = MovingAverageModel().predict(df)

In [5]:
df.loc[
    (df["name"] == "Jarrod_Bowen") & (df["season"] == "2020-21"),
    ["season", "name", "team", "GW", "total_points", "points_next_three", "points_next_five",
    "prediction_next_one", "prediction_next_three", "prediction_next_five"]
].head(10)

,season,name,team,GW,total_points,points_next_three,points_next_five,prediction_next_one,prediction_next_three,prediction_next_five
101248,2020-21,Jarrod_Bowen,West Ham,1,2,19,29,NaN,NaN,NaN
101249,2020-21,Jarrod_Bowen,West Ham,2,2,25,29,2.000000,6.0,10.000000
101250,2020-21,Jarrod_Bowen,West Ham,3,15,25,29,2.000000,6.0,10.000000
101251,2020-21,Jarrod_Bowen,West Ham,4,8,12,17,6.333333,19.0,31.666667
101252,2020-21,Jarrod_Bowen,West Ham,5,2,6,12,8.333333,25.0,41.666667
101253,2020-21,Jarrod_Bowen,West Ham,6,2,7,23,8.333333,25.0,41.666667
101254,2020-21,Jarrod_Bowen,West Ham,7,2,8,23,4.000000,12.0,20.000000
101255,2020-21,Jarrod_Bowen,West Ham,8,3,19,26,2.000000,6.0,10.000000
101256,2020-21,Jarrod_Bowen,West Ham,9,3,18,25,2.333333,7.0,11.666667
101257,2020-21,Jarrod_Bowen,West Ham,10,13,20,24,2.666667,8.0,13.333333

In [ ]:
from src.evaluate import AllMetrics

all_metrics = AllMetrics.from_dataframe(
    df=df,
    actual_col='points_next_three',
    predicted_col='prediction_next_three',
)

In [ ]:
all_metrics.summary()

    season  mean_absolute_error  rank_correlation
0  2016-17                3.008             0.727
1  2017-18                3.163             0.712
2  2018-19                3.256             0.694
3  2019-20                3.139             0.708
4  2020-21                2.927             0.725
5  2021-22                2.946             0.718
6  2022-23                2.736             0.742
7  2023-24                2.490             0.745
8  2024-25                2.701             0.757

In [ ]:
# Drill into a specific season
all_metrics.seasons['2023-24'].by_position

{'DEF': {'mean_absolute_error': 2.687, 'rank_correlation': 0.645},
 'FWD': {'mean_absolute_error': 2.727, 'rank_correlation': 0.786},
 'GK': {'mean_absolute_error': 1.582, 'rank_correlation': 0.833},
 'MID': {'mean_absolute_error': 2.513, 'rank_correlation': 0.775}}

In [ ]:
all_metrics.seasons['2023-24'].by_gameweek[10]

{'mean_absolute_error': 2.582, 'rank_correlation': 0.743}

In [ ]:
pd.DataFrame(all_metrics.seasons['2023-24'].by_gameweek).T

   mean_absolute_error rank_correlation
1                 None             None
2                3.323            0.712
3                2.849            0.733
4                2.597            0.749
5                2.774            0.718
6                2.657            0.728
7                2.387            0.764
8                2.546            0.763
9                2.572            0.755
10               2.582            0.743
11                2.57            0.721
12               2.638            0.726
13               2.719            0.713
14               2.685            0.739
15               2.675            0.746
16               2.474            0.758
17               2.766              0.7
18               2.869            0.731
19               2.644            0.754
20               2.709            0.722
21               2.785            0.667
22               2.665            0.717
23                 2.6            0.744
24               2.632            0.712
25               2.455            0.718
26               2.505            0.728
27               2.342            0.763
28               2.252            0.754
29               2.375            0.707
30               2.153            0.787
31               2.083            0.773
32               2.274            0.788
33               2.038             0.81
34               2.183            0.799
35               2.058            0.797
36               2.178            0.777
37               2.156            0.761
38               2.344            0.705